services:
  app:
    build: .
    container_name: fhun_tips
    image: wm-pickems:latest
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8090}:8090"
    env_file:
      - .env
    environment:
      - WMP_DEV=${WMP_DEV:-0}
    volumes:
      - pb_data:/pb_data

volumes:
  pb_data:
