// Package migrations holds the Go-code PocketBase schema migrations. Files are
// registered via init() and run by migratecmd (automigrate) on boot.
package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
	"github.com/pocketbase/pocketbase/tools/types"
)

// Collection NAMES (not ids). PocketBase forbids a collection name from
// matching any collection id, so ids are autogenerated and cross-collection
// relations are wired with the real ids captured after each Save.
const (
	nTeams          = "teams"
	nGroups         = "tournament_groups"
	nMatches        = "matches"
	nScoringConfigs = "scoring_configs"
	nLeagues        = "leagues"
	nLeagueMembers  = "league_members"
	nTips           = "tips"
	nForecasts      = "forecasts"
	nMatchScores    = "match_scores"
	nForecastScores = "forecast_scores"
	nAppMeta        = "app_meta"
)

func ptr(s string) *string { return types.Pointer(s) }

// goals is a 0..99 integer score field (nullable; not Required so unplayed
// matches and partial predictions are valid).
func goals(name string) *core.NumberField {
	return &core.NumberField{
		Name:    name,
		Min:     types.Pointer(0.0),
		Max:     types.Pointer(99.0),
		OnlyInt: true,
	}
}

func init() {
	m.Register(up0001, down0001)
}

func up0001(app core.App) error {
	users, err := app.FindCollectionByNameOrId("users")
	if err != nil {
		return err
	}
	usersID := users.Id

	// ---- teams ----
	teams := core.NewBaseCollection(nTeams)
	teams.ListRule = ptr("")
	teams.ViewRule = ptr("")
	teams.Fields.Add(&core.TextField{Name: "fifaCode", Required: true, Max: 3})
	teams.Fields.Add(&core.TextField{Name: "name", Required: true, Max: 100})
	teams.Fields.Add(&core.TextField{Name: "iso2", Max: 8}) // flag-icons name, e.g. "mx" or "gb-sct"
	teams.Fields.Add(&core.TextField{Name: "confederation", Max: 16})
	teams.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	teams.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	teams.AddIndex("idx_teams_fifaCode", true, "fifaCode", "")
	if err := app.Save(teams); err != nil {
		return err
	}
	teamsID := teams.Id

	// ---- tournament_groups (A..L) ----
	groups := core.NewBaseCollection(nGroups)
	groups.ListRule = ptr("")
	groups.ViewRule = ptr("")
	groups.Fields.Add(&core.TextField{Name: "letter", Required: true, Max: 2})
	groups.Fields.Add(&core.RelationField{Name: "teams", CollectionId: teamsID, MaxSelect: 8})
	groups.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	groups.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	groups.AddIndex("idx_groups_letter", true, "letter", "")
	if err := app.Save(groups); err != nil {
		return err
	}

	// ---- matches ----
	matches := core.NewBaseCollection(nMatches)
	matches.ListRule = ptr("")
	matches.ViewRule = ptr("")
	matches.Fields.Add(&core.TextField{Name: "extId", Required: true, Max: 64})
	matches.Fields.Add(&core.SelectField{
		Name: "stage", Required: true, MaxSelect: 1,
		Values: []string{"group", "R32", "R16", "QF", "SF", "3RD", "FINAL"},
	})
	matches.Fields.Add(&core.NumberField{Name: "num", OnlyInt: true}) // KO match number 73..104
	matches.Fields.Add(&core.TextField{Name: "groupLetter", Max: 2})
	matches.Fields.Add(&core.TextField{Name: "roundLabel", Max: 32})
	matches.Fields.Add(&core.RelationField{Name: "homeTeam", CollectionId: teamsID, MaxSelect: 1})
	matches.Fields.Add(&core.RelationField{Name: "awayTeam", CollectionId: teamsID, MaxSelect: 1})
	matches.Fields.Add(&core.TextField{Name: "homeLabel", Max: 32}) // e.g. "1A", "3A/B/C/D/F", "W74"
	matches.Fields.Add(&core.TextField{Name: "awayLabel", Max: 32})
	matches.Fields.Add(&core.DateField{Name: "kickoff", Required: true})
	matches.Fields.Add(&core.TextField{Name: "tvChannel", Max: 8})
	matches.Fields.Add(&core.SelectField{
		Name: "status", Required: true, MaxSelect: 1,
		Values: []string{"scheduled", "live", "finished", "postponed", "cancelled"},
	})
	matches.Fields.Add(goals("ftHome"))
	matches.Fields.Add(goals("ftAway"))
	matches.Fields.Add(goals("etHome"))
	matches.Fields.Add(goals("etAway"))
	matches.Fields.Add(goals("penHome"))
	matches.Fields.Add(goals("penAway"))
	matches.Fields.Add(&core.RelationField{Name: "penWinner", CollectionId: teamsID, MaxSelect: 1})
	matches.Fields.Add(&core.RelationField{Name: "advancer", CollectionId: teamsID, MaxSelect: 1})
	matches.Fields.Add(&core.DateField{Name: "finalizedAt"})
	matches.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	matches.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	matches.AddIndex("idx_matches_extId", true, "extId", "")
	matches.AddIndex("idx_matches_kickoff", false, "kickoff", "")
	if err := app.Save(matches); err != nil {
		return err
	}
	matchesID := matches.Id

	// ---- scoring_configs ----
	sc := core.NewBaseCollection(nScoringConfigs)
	sc.ListRule = ptr("")
	sc.ViewRule = ptr("")
	sc.Fields.Add(&core.TextField{Name: "name", Required: true, Max: 64})
	sc.Fields.Add(&core.BoolField{Name: "isDefault"})
	sc.Fields.Add(&core.JSONField{Name: "config", MaxSize: 20000})
	sc.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	sc.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	if err := app.Save(sc); err != nil {
		return err
	}
	scID := sc.Id

	// ---- leagues ----
	leagues := core.NewBaseCollection(nLeagues)
	authed := "@request.auth.id != ''"
	leagues.ListRule = ptr(authed)
	leagues.ViewRule = ptr(authed)
	leagues.CreateRule = ptr(authed)
	leagues.UpdateRule = ptr("@request.auth.id = owner")
	leagues.DeleteRule = ptr("@request.auth.id = owner")
	leagues.Fields.Add(&core.TextField{Name: "name", Required: true, Max: 64})
	leagues.Fields.Add(&core.TextField{Name: "inviteCode", Required: true, Max: 12})
	leagues.Fields.Add(&core.RelationField{Name: "owner", CollectionId: usersID, MaxSelect: 1, Required: true})
	leagues.Fields.Add(&core.RelationField{Name: "scoringConfig", CollectionId: scID, MaxSelect: 1})
	leagues.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	leagues.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	leagues.AddIndex("idx_leagues_inviteCode", true, "inviteCode", "")
	if err := app.Save(leagues); err != nil {
		return err
	}
	leaguesID := leagues.Id

	// ---- league_members ----
	lm := core.NewBaseCollection(nLeagueMembers)
	lm.ListRule = ptr(authed)
	lm.ViewRule = ptr(authed)
	lm.Fields.Add(&core.RelationField{Name: "league", CollectionId: leaguesID, MaxSelect: 1, Required: true, CascadeDelete: true})
	lm.Fields.Add(&core.RelationField{Name: "user", CollectionId: usersID, MaxSelect: 1, Required: true, CascadeDelete: true})
	lm.Fields.Add(&core.SelectField{Name: "role", MaxSelect: 1, Values: []string{"owner", "member"}})
	lm.Fields.Add(&core.AutodateField{Name: "joinedAt", OnCreate: true})
	lm.AddIndex("idx_lm_league_user", true, "league, user", "")
	if err := app.Save(lm); err != nil {
		return err
	}

	// ---- tips (per-match prediction) ----
	tips := core.NewBaseCollection(nTips)
	tips.ListRule = ptr(authed) // tightened to own-only in 0002
	tips.ViewRule = ptr(authed)
	tips.CreateRule = ptr("@request.auth.id = user")
	tips.UpdateRule = ptr("@request.auth.id = user")
	tips.DeleteRule = ptr("@request.auth.id = user")
	tips.Fields.Add(&core.RelationField{Name: "user", CollectionId: usersID, MaxSelect: 1, Required: true, CascadeDelete: true})
	tips.Fields.Add(&core.RelationField{Name: "match", CollectionId: matchesID, MaxSelect: 1, Required: true, CascadeDelete: true})
	tips.Fields.Add(goals("ftHome"))
	tips.Fields.Add(goals("ftAway"))
	tips.Fields.Add(goals("etHome"))
	tips.Fields.Add(goals("etAway"))
	tips.Fields.Add(&core.RelationField{Name: "penWinner", CollectionId: teamsID, MaxSelect: 1})
	tips.Fields.Add(&core.RelationField{Name: "advancer", CollectionId: teamsID, MaxSelect: 1})
	tips.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	tips.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	tips.AddIndex("idx_tips_user_match", true, "user, match", "")
	if err := app.Save(tips); err != nil {
		return err
	}

	// ---- forecasts (one pre-tournament prediction per user) ----
	fc := core.NewBaseCollection(nForecasts)
	fc.ListRule = ptr(authed) // refined in Phase 4 (visible to league only after lock)
	fc.ViewRule = ptr(authed)
	fc.CreateRule = ptr("@request.auth.id = user")
	fc.UpdateRule = ptr("@request.auth.id = user")
	fc.DeleteRule = ptr("@request.auth.id = user")
	fc.Fields.Add(&core.RelationField{Name: "user", CollectionId: usersID, MaxSelect: 1, Required: true, CascadeDelete: true})
	fc.Fields.Add(&core.JSONField{Name: "groupOrder", MaxSize: 20000})      // {"A":[teamId x4],...}
	fc.Fields.Add(&core.JSONField{Name: "thirdQualifiers", MaxSize: 20000}) // {"slot":"teamId",...}
	fc.Fields.Add(&core.JSONField{Name: "bracket", MaxSize: 40000})         // {"matchNum":"teamId",...}
	fc.Fields.Add(&core.DateField{Name: "lockedAt"})
	fc.Fields.Add(&core.AutodateField{Name: "created", OnCreate: true})
	fc.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	fc.AddIndex("idx_forecasts_user", true, "user", "")
	if err := app.Save(fc); err != nil {
		return err
	}

	// ---- match_scores (computed per user/match/config) ----
	ms := core.NewBaseCollection(nMatchScores)
	ms.ListRule = ptr(authed)
	ms.ViewRule = ptr(authed)
	ms.Fields.Add(&core.RelationField{Name: "user", CollectionId: usersID, MaxSelect: 1, Required: true, CascadeDelete: true})
	ms.Fields.Add(&core.RelationField{Name: "match", CollectionId: matchesID, MaxSelect: 1, Required: true, CascadeDelete: true})
	ms.Fields.Add(&core.RelationField{Name: "config", CollectionId: scID, MaxSelect: 1, Required: true})
	ms.Fields.Add(&core.NumberField{Name: "points", OnlyInt: true})
	ms.Fields.Add(&core.JSONField{Name: "components", MaxSize: 4000})
	ms.Fields.Add(&core.AutodateField{Name: "computedAt", OnCreate: true, OnUpdate: true})
	ms.AddIndex("idx_ms_user_match_config", true, "user, match, config", "")
	if err := app.Save(ms); err != nil {
		return err
	}

	// ---- forecast_scores (computed per user/config, updated progressively) ----
	fs := core.NewBaseCollection(nForecastScores)
	fs.ListRule = ptr(authed)
	fs.ViewRule = ptr(authed)
	fs.Fields.Add(&core.RelationField{Name: "user", CollectionId: usersID, MaxSelect: 1, Required: true, CascadeDelete: true})
	fs.Fields.Add(&core.RelationField{Name: "config", CollectionId: scID, MaxSelect: 1, Required: true})
	fs.Fields.Add(&core.NumberField{Name: "points", OnlyInt: true})
	fs.Fields.Add(&core.JSONField{Name: "breakdown", MaxSize: 20000})
	fs.Fields.Add(&core.AutodateField{Name: "computedAt", OnCreate: true, OnUpdate: true})
	fs.AddIndex("idx_fs_user_config", true, "user, config", "")
	if err := app.Save(fs); err != nil {
		return err
	}

	// ---- app_meta (sync bookkeeping; key/value) ----
	meta := core.NewBaseCollection(nAppMeta)
	meta.Fields.Add(&core.TextField{Name: "key", Required: true, Max: 64})
	meta.Fields.Add(&core.JSONField{Name: "value", MaxSize: 4000})
	meta.Fields.Add(&core.AutodateField{Name: "updated", OnCreate: true, OnUpdate: true})
	meta.AddIndex("idx_app_meta_key", true, "key", "")
	if err := app.Save(meta); err != nil {
		return err
	}

	return nil
}

func down0001(app core.App) error {
	for _, name := range []string{
		nAppMeta, nForecastScores, nMatchScores, nForecasts, nTips,
		nLeagueMembers, nLeagues, nScoringConfigs, nMatches, nGroups, nTeams,
	} {
		if c, err := app.FindCollectionByNameOrId(name); err == nil {
			if err := app.Delete(c); err != nil {
				return err
			}
		}
	}
	return nil
}
