import { isRuntimeEnglish } from './runtimeLanguage';

const norwegianTeamNames: Record<string, string> = {
	MEX: 'Mexico',
	RSA: 'Sør-Afrika',
	KOR: 'Sør-Korea',
	CZE: 'Tsjekkia',
	CAN: 'Canada',
	BIH: 'Bosnia-Hercegovina',
	QAT: 'Qatar',
	SUI: 'Sveits',
	BRA: 'Brasil',
	MAR: 'Marokko',
	HAI: 'Haiti',
	SCO: 'Skottland',
	USA: 'USA',
	PAR: 'Paraguay',
	AUS: 'Australia',
	TUR: 'Tyrkia',
	GER: 'Tyskland',
	CUW: 'Curaçao',
	CIV: 'Elfenbenskysten',
	ECU: 'Ecuador',
	NED: 'Nederland',
	JPN: 'Japan',
	SWE: 'Sverige',
	TUN: 'Tunisia',
	BEL: 'Belgia',
	EGY: 'Egypt',
	IRN: 'Iran',
	NZL: 'New Zealand',
	ESP: 'Spania',
	CPV: 'Kapp Verde',
	KSA: 'Saudi-Arabia',
	URU: 'Uruguay',
	FRA: 'Frankrike',
	SEN: 'Senegal',
	IRQ: 'Irak',
	NOR: 'Norge',
	ARG: 'Argentina',
	ALG: 'Algerie',
	AUT: 'Østerrike',
	JOR: 'Jordan',
	POR: 'Portugal',
	COD: 'DR Kongo',
	UZB: 'Usbekistan',
	COL: 'Colombia',
	ENG: 'England',
	CRO: 'Kroatia',
	GHA: 'Ghana',
	PAN: 'Panama'
};

const englishTeamNames: Record<string, string> = {
	MEX: 'Mexico',
	RSA: 'South Africa',
	KOR: 'South Korea',
	CZE: 'Czech Republic',
	CAN: 'Canada',
	BIH: 'Bosnia and Herzegovina',
	QAT: 'Qatar',
	SUI: 'Switzerland',
	BRA: 'Brazil',
	MAR: 'Morocco',
	HAI: 'Haiti',
	SCO: 'Scotland',
	USA: 'USA',
	PAR: 'Paraguay',
	AUS: 'Australia',
	TUR: 'Turkey',
	GER: 'Germany',
	CUW: 'Curaçao',
	CIV: 'Ivory Coast',
	ECU: 'Ecuador',
	NED: 'Netherlands',
	JPN: 'Japan',
	SWE: 'Sweden',
	TUN: 'Tunisia',
	BEL: 'Belgium',
	EGY: 'Egypt',
	IRN: 'Iran',
	NZL: 'New Zealand',
	ESP: 'Spain',
	CPV: 'Cape Verde',
	KSA: 'Saudi Arabia',
	URU: 'Uruguay',
	FRA: 'France',
	SEN: 'Senegal',
	IRQ: 'Iraq',
	NOR: 'Norway',
	ARG: 'Argentina',
	ALG: 'Algeria',
	AUT: 'Austria',
	JOR: 'Jordan',
	POR: 'Portugal',
	COD: 'DR Congo',
	UZB: 'Uzbekistan',
	COL: 'Colombia',
	ENG: 'England',
	CRO: 'Croatia',
	GHA: 'Ghana',
	PAN: 'Panama'
};

export function teamDisplayName(
	team: { name?: string; fifaCode?: string } | null | undefined,
	fallback = ''
) {
	if (!team) return fallback;
	const names = isRuntimeEnglish() ? englishTeamNames : norwegianTeamNames;
	return (team.fifaCode && names[team.fifaCode]) || team.name || fallback;
}